id: P004356
initial_creation_type: ocr
source_metadata:
  id: bdr:W10979
  title: གསུང་ཐོར་བུ། ཀུན་དགའ་བསྟན་འཛིན།
  author: ''
  volumes:
    5eb08b0a059a48c896b6498fc3768d69:
      image_group_id: I1PD96699
      title: ''
      volume_number: 1
      total_pages: 618
      base_file: v001.txt
    6ec36427ba5d4dc8a9daa8a718012f09:
      image_group_id: I1PD96700
      title: ''
      volume_number: 2
      total_pages: 656
      base_file: v002.txt
    5396a68d78d7463298daf2f4180fba8f:
      image_group_id: I1PD96701
      title: ''
      volume_number: 3
      total_pages: 566
      base_file: v003.txt
