id: IE0B23734
legacy_id: P004356
ocr_import_info:
  bdrc_scan_id: W10979
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T04:35:04'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T13:40:35.098414+00:00'
last_modified: 2022-08-30 21:42:51.758507
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W10979
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW10979
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་ཐོར་བུ། ཀུན་དགའ་བསྟན་འཛིན།
  author: ཁམས་སྤྲུལ ༠༣་ཀུན་དགའ་བསྟན་འཛིན།
statistics:
  ocr_word_mean_confidence_index: 0.7447050808962592
  ocr_word_median_confidence_index: 0.8299999833106995
quality: null
bases:
  I1PD96699:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD96699
      total_pages: 618
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD96699.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.7290880869959571
    legacy_id: v001
  I1PD96701:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD96701
      total_pages: 566
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1PD96701.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7189367719117536
    legacy_id: v003
  I1PD96700:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD96700
      total_pages: 656
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1PD96700.txt
    statistics:
      ocr_word_median_confidence_index: 0.8799999952316284
      ocr_word_mean_confidence_index: 0.7877076348371465
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
