id: IE0B23734
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T04:38:48+00:00'
last_modified: '2022-06-07T22:15:30.462266+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W10979
  title: གསུང་ཐོར་བུ། ཀུན་དགའ་བསྟན་འཛིན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6B32:
      image_group_id: I1PD96699
      title: ''
      total_pages: 618
      order: 1
      base_file: 6B32.txt
    655D:
      image_group_id: I1PD96700
      title: ''
      total_pages: 656
      order: 2
      base_file: 655D.txt
    55BB:
      image_group_id: I1PD96701
      title: ''
      total_pages: 566
      order: 3
      base_file: 55BB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
